---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "wazuh.fullname" . }}-elasticsearch
spec:
  type: ClusterIP
  ports:
    - name: tcp-http
      protocol: TCP
      port: 9200
  selector:
    app: {{ include "wazuh.fullname" . }}-elasticsearch
    {{- include "wazuh.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "wazuh.fullname" . }}-elasticsearch-headless
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: tcp-http
      protocol: TCP
      port: 9200
  selector:
    app: {{ include "wazuh.fullname" . }}-elasticsearch
    {{- include "wazuh.selectorLabels" . | nindent 4 }}
