apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wazuh.fullname" . }}-elasticsearch-secrets
  labels:
    {{- include "wazuh.labels" . | nindent 4 }}
data:
  elasticsearch_username: {{ .Values.credentials.elastic_credential.elasticsearch_username | b64enc | quote }}
  elasticsearch_password: {{ .Values.credentials.elastic_credential.elasticsearch_password | b64enc | quote }}
