apiVersion: v1
kind: Secret
metadata:
  name: regcred
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJmcmJyZXZkb2NrZXJyZWdpc3RyeS52b2ljZS5hbGUtaW50ZXJuYXRpb25hbC5jb206ODIwMCI6IHsKCQkJImF1dGgiOiAiVGtkUFZpMWtaWEJzYjNsdFpXNTBPbU52ZFZkbU4xQndTamx2VDFGcU9WbFliMHB1IgoJCX0sCgkJImthZmthLm5ldHdvcmthbGUuY29tOjUwMDAiOiB7CgkJCSJhdXRoIjogIllXUnRhVzQ2VEc5ak1VSnlaVkJoYzNNeUlRPT0iCgkJfSwKCQkicmVwby5teW92Y2xvdWQuY29tOjUwMDAiOiB7CgkJCSJhdXRoIjogImNtOXVZVzQ2T0ZwQk5YUklSMVp0IgoJCX0KCX0sCgkiSHR0cEhlYWRlcnMiOiB7CgkJIlVzZXItQWdlbnQiOiAiRG9ja2VyLUNsaWVudC8xOS4wMy40IChsaW51eCkiCgl9Cn0=
