---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "wazuh.fullname" . }}-kibana
  labels:
    {{- include "wazuh.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - name: tcp-kibana
    port: 5601
    targetPort: 5601
    protocol: TCP
  selector:
    app: {{ include "wazuh.fullname" . }}-kibana
    {{- include "wazuh.selectorLabels" . | nindent 4 }}
