{{- if .Values.ingress.kibana.enabled -}}
{{- $ingressPath := .Values.ingress.kibana.path -}}
{{- $serviceName := include "wazuh.fullname" . -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "wazuh.fullname" . }}-kibana-ingress
  labels:
    {{- include "wazuh.labels" . | nindent 4 }}

{{- with .Values.ingress.kibana.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.kibana.tls }}
  tls:
  {{- range .Values.ingress.kibana.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.kibana.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            pathType: Prefix
            backend:
              service:
                name: {{ $serviceName }}-kibana
                port:
                  number: 5601

  {{- end }}
{{- end }}
