apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wazuh.fullname" . }}-wazuh-secrets
  labels:
    {{- include "wazuh.labels" . | nindent 4 }}
data:
  api_username: {{ .Values.credentials.wazuh.api_username | b64enc | quote }}
  api_password: {{ .Values.credentials.wazuh.api_password | b64enc | quote }}
