apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wazuh.fullname" . }}-wazuh-manager-conf
  labels:
    app: {{ include "wazuh.fullname" . }}-wazuh-manager
    {{- include "wazuh.labels" . | nindent 4 }}
data: 
  ossec.conf: |
    {{- index .Values.config.wazuh "ossec.xml" | nindent 4 }}

  local_decoder.xml: |
    {{- index .Values.config.wazuh "local_decoder.xml" | nindent 4 }}

  local_rules.xml: |
    {{- index .Values.config.wazuh "local_rules.xml" | nindent 4 }}
